<aura:component implements 	= "force:appHostable,flexipage:availableForAllPageTypes,flexipage:availableForRecordHome,force:hasRecordId,forceCommunity:availableForAllPageTypes,force:lightningQuickAction" 
                controller 	= "CTX_ErrorBanner_Opportunity" 
                access		= "global" >
    
    <aura:handler name='init' value='{!this}' action='{!c.doInit}' />
    
    <aura:attribute name="loaded" 		type="Boolean" default="true" />    
    <aura:attribute name="isSuccess" 	type="Boolean" />
    <aura:attribute name="recordId" 	type="String" />
    <aura:attribute name="returnResult" type="List" />
    
    <div class="exampleHolder">
        <aura:if isTrue="{! v.loaded }">
            <lightning:spinner alternativeText="Loading" />
            <aura:set attribute="else">
                <aura:if isTrue="{!v.isSuccess}">
                    
                    <ui:message title="Error Monitoring" severity="confirm" closable="false">
                        You don't have any error on this record.
                    </ui:message>
                    
                    <aura:set attribute="else">
                        <ui:message title="Error Monitoring" severity="error" closable="false">
                            <aura:iteration items="{!v.returnResult}" var="item" indexVar="key">
                                <b>{!item.key}: </b> <br/>{!item.value} <br/><br/>
                            </aura:iteration>
                        </ui:message>
                    </aura:set>
                    
                </aura:if>
            </aura:set>
        </aura:if>
    </div>
    
</aura:component>